# Generated by Django 5.2.13 on 2026-04-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nps', models.IntegerField()),
                ('comentario', models.TextField()),
                ('riesgo_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('en_riesgo', models.BooleanField(default=False)),
                ('analisis_ia', models.TextField(blank=True, null=True)),
                ('estrategia_ia', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
