# Generated by Django 5.2.4 on 2026-04-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='num_quejas',
            field=models.IntegerField(default=0),
        ),
    ]
