# Generated by Django 5.2.13 on 2026-04-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0002_cliente_num_quejas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='riesgo_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
