# Generated by Django 5.2.13 on 2026-04-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0003_alter_cliente_riesgo_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='riesgo_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
