# Generated by Django 5.2.13 on 2026-04-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0004_alter_cliente_riesgo_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
